---
title: "DataCleaning"
author: "YS"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load library}
library(tidyverse)
```


# data cleaning

We obtained the most recent available raw Airbnb data for New York City from http://insideairbnb.com/get-the-data.html. The csv. file is more than 180MB

```{r }
#data<-read_csv("listings_201909.csv", na=c("","NA","N/A"))
data<-read_csv(file.choose(), na=c("","NA","N/A"))

dat<-data%>%
  select(-c(scrape_id:xl_picture_url))%>%
  select(-host_url, -host_name, -host_location, -host_about, -host_acceptance_rate, -host_thumbnail_url, -host_picture_url, -host_neighbourhood)%>%
  select(-street,-city,-state, -market, -smart_location, -country, -country_code)%>%
  select(-jurisdiction_names, -license,-weekly_price,-monthly_price, -square_feet)%>%
  select(-c(calendar_updated:calendar_last_scraped)) 

dim(dat)  #48377    62

dat<-dat%>%
  mutate_at(c("host_response_rate","extra_people","price","security_deposit","cleaning_fee"),str_remove_all,pattern="[%$]")%>%
  mutate_at(c("host_response_rate","extra_people","price","security_deposit","cleaning_fee"),as.numeric)


dat1<-dat%>%filter(!is.na(first_review))
dim(dat1) #38726    62

write_csv(dat1,"./data/airbnb_201909.csv")
```

```{r amenities}
split_amenities<-function(x){
  x<-str_replace_all(x,"[{}]",",") #remove {}
  temp<-str_split(x,"\\\"")[[1]] #split by \"
  temp[str_starts(temp,"[,]") | str_ends(temp,"[,]")]<-str_replace_all(temp[str_starts(temp,"[,]") | str_ends(temp,"[,]")],"[,]","|")
  temp<-str_remove(temp,"^\\|")
  temp<-str_remove(temp,"\\|$")
  temp<-temp[temp!=""]
  out<-paste(temp,collapse = "|")
  return(out)
}

#id==57166
#38 list has no amenities
dat2<-dat1%>%select(id, amenities)%>%
  rowwise()%>%
  mutate(amenity = split_amenities(amenities))
dat3<-dat2%>%separate_rows(amenity,sep="\\|")

length(unique(dat3$amenity))  #130, including 1 "" for lists with no amenities

write_csv(dat3%>%select(-amenities),"./data/amenities_201909.csv")
```


```{r}
colSums(is.na(df))
```